version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - ./data/app_data:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - ./data/document_data:/var/www/onlyoffice/Data
      - ./data/document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/app_data:/var/www/html
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=you_password
     - POSTGRES_DB=nextcloud
    volumes:
      - postgresql:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    ports:
      - 53603:53603
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: you_mail@domain.kz
      PGADMIN_DEFAULT_PASSWORD: you_password
volumes:
  document_data:
  document_log:
  app_data:
  postgresql:
